server:
  port: 8088
spring:
  datasource:
    auth-mgmt-source:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.232.130:3306/auth_mgmt?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      minIdle: 5
      maxPoolSize: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      testQuery: SELECT 1
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
